@startuml
'https://plantuml.com/activity-diagram-beta

start

repeat :generalLoop();
:checkPrinters();
if (currentDisplay is "general_frame") then (true)
  :screen_frame();
  :for printer in printersAdresses;
  if (printer is running) then (true)
    :generalFrameOn();
    :get printer information;
    fork
    :display Remaining time;
    fork again
    :display Percentage value;
    fork again
    :display Gradient border;
    fork again
    :display miniature;
    end merge
  else (false)
    :generalFrameOff();
    :get cluster history information;
    fork
    :display Final state;
    fork again
    :display Percentage value;
    fork again
    :display Gradient border;
    fork again
    :display miniature;
    end merge
  endif
else (false)
:staticData();
:display Camera + Miniature;
repeat :printerLoop;
fork
:completeProcessPrinter();
fork again
:display printer name;
end merge
:get printer information;
fork
:display Remaining time;
fork again
:display Percentage value;
fork again
:display Head and bed temperature;
fork again
:Set color for head and bed logo;
fork again
if (end of job) then (true)
:blink lights + confetti screen;
endif
end merge
backward: Every 10 seconds;
repeat while (printer is currently displaying)
endif
backward: Every minute currentDisplay is increased;
repeat while (is not shutdown)
stop

@enduml
